# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto.product import client_grpc_pb2 as proto_dot_product_dot_client__grpc__pb2


class productServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.saveProduct = channel.unary_unary(
                '/productService/saveProduct',
                request_serializer=proto_dot_product_dot_client__grpc__pb2.ProductSaveRequest.SerializeToString,
                response_deserializer=proto_dot_product_dot_client__grpc__pb2.Response.FromString,
                )
        self.updateProduct = channel.unary_unary(
                '/productService/updateProduct',
                request_serializer=proto_dot_product_dot_client__grpc__pb2.ProductUpdateRequest.SerializeToString,
                response_deserializer=proto_dot_product_dot_client__grpc__pb2.Response.FromString,
                )
        self.getProduct = channel.unary_unary(
                '/productService/getProduct',
                request_serializer=proto_dot_product_dot_client__grpc__pb2.idProduct.SerializeToString,
                response_deserializer=proto_dot_product_dot_client__grpc__pb2.ProductResponse.FromString,
                )


class productServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def saveProduct(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def updateProduct(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getProduct(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_productServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'saveProduct': grpc.unary_unary_rpc_method_handler(
                    servicer.saveProduct,
                    request_deserializer=proto_dot_product_dot_client__grpc__pb2.ProductSaveRequest.FromString,
                    response_serializer=proto_dot_product_dot_client__grpc__pb2.Response.SerializeToString,
            ),
            'updateProduct': grpc.unary_unary_rpc_method_handler(
                    servicer.updateProduct,
                    request_deserializer=proto_dot_product_dot_client__grpc__pb2.ProductUpdateRequest.FromString,
                    response_serializer=proto_dot_product_dot_client__grpc__pb2.Response.SerializeToString,
            ),
            'getProduct': grpc.unary_unary_rpc_method_handler(
                    servicer.getProduct,
                    request_deserializer=proto_dot_product_dot_client__grpc__pb2.idProduct.FromString,
                    response_serializer=proto_dot_product_dot_client__grpc__pb2.ProductResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'productService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class productService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def saveProduct(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/productService/saveProduct',
            proto_dot_product_dot_client__grpc__pb2.ProductSaveRequest.SerializeToString,
            proto_dot_product_dot_client__grpc__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def updateProduct(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/productService/updateProduct',
            proto_dot_product_dot_client__grpc__pb2.ProductUpdateRequest.SerializeToString,
            proto_dot_product_dot_client__grpc__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getProduct(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/productService/getProduct',
            proto_dot_product_dot_client__grpc__pb2.idProduct.SerializeToString,
            proto_dot_product_dot_client__grpc__pb2.ProductResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
