# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/product/client_grpc.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fproto/product/client_grpc.proto\"\x17\n\tidProduct\x12\n\n\x02id\x18\x01 \x01(\x03\"l\n\x12ProductSaveRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x11\n\tlistPhoto\x18\x04 \x03(\t\x12\r\n\x05price\x18\x05 \x01(\x02\x12\x11\n\tavailable\x18\x06 \x01(\x05\"z\n\x14ProductUpdateRequest\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x11\n\tlistPhoto\x18\x05 \x03(\t\x12\r\n\x05price\x18\x06 \x01(\x02\x12\x11\n\tavailable\x18\x07 \x01(\x05\"b\n\x0fProductResponse\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\r\n\x05price\x18\x05 \x01(\x02\x12\x11\n\tavailable\x18\x06 \x01(\x05\"\x1b\n\x08Response\x12\x0f\n\x07message\x18\x01 \x01(\t2\xa4\x01\n\x0eproductService\x12/\n\x0bsaveProduct\x12\x13.ProductSaveRequest\x1a\t.Response\"\x00\x12\x33\n\rupdateProduct\x12\x15.ProductUpdateRequest\x1a\t.Response\"\x00\x12,\n\ngetProduct\x12\n.idProduct\x1a\x10.ProductResponse\"\x00\x62\x06proto3')



_IDPRODUCT = DESCRIPTOR.message_types_by_name['idProduct']
_PRODUCTSAVEREQUEST = DESCRIPTOR.message_types_by_name['ProductSaveRequest']
_PRODUCTUPDATEREQUEST = DESCRIPTOR.message_types_by_name['ProductUpdateRequest']
_PRODUCTRESPONSE = DESCRIPTOR.message_types_by_name['ProductResponse']
_RESPONSE = DESCRIPTOR.message_types_by_name['Response']
idProduct = _reflection.GeneratedProtocolMessageType('idProduct', (_message.Message,), {
  'DESCRIPTOR' : _IDPRODUCT,
  '__module__' : 'proto.product.client_grpc_pb2'
  # @@protoc_insertion_point(class_scope:idProduct)
  })
_sym_db.RegisterMessage(idProduct)

ProductSaveRequest = _reflection.GeneratedProtocolMessageType('ProductSaveRequest', (_message.Message,), {
  'DESCRIPTOR' : _PRODUCTSAVEREQUEST,
  '__module__' : 'proto.product.client_grpc_pb2'
  # @@protoc_insertion_point(class_scope:ProductSaveRequest)
  })
_sym_db.RegisterMessage(ProductSaveRequest)

ProductUpdateRequest = _reflection.GeneratedProtocolMessageType('ProductUpdateRequest', (_message.Message,), {
  'DESCRIPTOR' : _PRODUCTUPDATEREQUEST,
  '__module__' : 'proto.product.client_grpc_pb2'
  # @@protoc_insertion_point(class_scope:ProductUpdateRequest)
  })
_sym_db.RegisterMessage(ProductUpdateRequest)

ProductResponse = _reflection.GeneratedProtocolMessageType('ProductResponse', (_message.Message,), {
  'DESCRIPTOR' : _PRODUCTRESPONSE,
  '__module__' : 'proto.product.client_grpc_pb2'
  # @@protoc_insertion_point(class_scope:ProductResponse)
  })
_sym_db.RegisterMessage(ProductResponse)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'proto.product.client_grpc_pb2'
  # @@protoc_insertion_point(class_scope:Response)
  })
_sym_db.RegisterMessage(Response)

_PRODUCTSERVICE = DESCRIPTOR.services_by_name['productService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _IDPRODUCT._serialized_start=35
  _IDPRODUCT._serialized_end=58
  _PRODUCTSAVEREQUEST._serialized_start=60
  _PRODUCTSAVEREQUEST._serialized_end=168
  _PRODUCTUPDATEREQUEST._serialized_start=170
  _PRODUCTUPDATEREQUEST._serialized_end=292
  _PRODUCTRESPONSE._serialized_start=294
  _PRODUCTRESPONSE._serialized_end=392
  _RESPONSE._serialized_start=394
  _RESPONSE._serialized_end=421
  _PRODUCTSERVICE._serialized_start=424
  _PRODUCTSERVICE._serialized_end=588
# @@protoc_insertion_point(module_scope)
