# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto.user import client_grpc_pb2 as proto_dot_user_dot_client__grpc__pb2


class userServiceStub(object):
    """////USER
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.findCurrentUser = channel.unary_unary(
                '/userService/findCurrentUser',
                request_serializer=proto_dot_user_dot_client__grpc__pb2.CurrentUser.SerializeToString,
                response_deserializer=proto_dot_user_dot_client__grpc__pb2.ResponseObjectUserData.FromString,
                )
        self.findUserByUsername = channel.unary_unary(
                '/userService/findUserByUsername',
                request_serializer=proto_dot_user_dot_client__grpc__pb2.UserToFind.SerializeToString,
                response_deserializer=proto_dot_user_dot_client__grpc__pb2.ResponseObjectUserData.FromString,
                )
        self.createNewUser = channel.unary_unary(
                '/userService/createNewUser',
                request_serializer=proto_dot_user_dot_client__grpc__pb2.UserRequest.SerializeToString,
                response_deserializer=proto_dot_user_dot_client__grpc__pb2.ResponseObjectUserData.FromString,
                )
        self.getList = channel.unary_unary(
                '/userService/getList',
                request_serializer=proto_dot_user_dot_client__grpc__pb2.Empty.SerializeToString,
                response_deserializer=proto_dot_user_dot_client__grpc__pb2.ResponseUserList.FromString,
                )


class userServiceServicer(object):
    """////USER
    """

    def findCurrentUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def findUserByUsername(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def createNewUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_userServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'findCurrentUser': grpc.unary_unary_rpc_method_handler(
                    servicer.findCurrentUser,
                    request_deserializer=proto_dot_user_dot_client__grpc__pb2.CurrentUser.FromString,
                    response_serializer=proto_dot_user_dot_client__grpc__pb2.ResponseObjectUserData.SerializeToString,
            ),
            'findUserByUsername': grpc.unary_unary_rpc_method_handler(
                    servicer.findUserByUsername,
                    request_deserializer=proto_dot_user_dot_client__grpc__pb2.UserToFind.FromString,
                    response_serializer=proto_dot_user_dot_client__grpc__pb2.ResponseObjectUserData.SerializeToString,
            ),
            'createNewUser': grpc.unary_unary_rpc_method_handler(
                    servicer.createNewUser,
                    request_deserializer=proto_dot_user_dot_client__grpc__pb2.UserRequest.FromString,
                    response_serializer=proto_dot_user_dot_client__grpc__pb2.ResponseObjectUserData.SerializeToString,
            ),
            'getList': grpc.unary_unary_rpc_method_handler(
                    servicer.getList,
                    request_deserializer=proto_dot_user_dot_client__grpc__pb2.Empty.FromString,
                    response_serializer=proto_dot_user_dot_client__grpc__pb2.ResponseUserList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'userService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class userService(object):
    """////USER
    """

    @staticmethod
    def findCurrentUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/userService/findCurrentUser',
            proto_dot_user_dot_client__grpc__pb2.CurrentUser.SerializeToString,
            proto_dot_user_dot_client__grpc__pb2.ResponseObjectUserData.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def findUserByUsername(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/userService/findUserByUsername',
            proto_dot_user_dot_client__grpc__pb2.UserToFind.SerializeToString,
            proto_dot_user_dot_client__grpc__pb2.ResponseObjectUserData.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def createNewUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/userService/createNewUser',
            proto_dot_user_dot_client__grpc__pb2.UserRequest.SerializeToString,
            proto_dot_user_dot_client__grpc__pb2.ResponseObjectUserData.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/userService/getList',
            proto_dot_user_dot_client__grpc__pb2.Empty.SerializeToString,
            proto_dot_user_dot_client__grpc__pb2.ResponseUserList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
