# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\"\x07\n\x05\x45mpty\"=\n\x07UserDto\x12\x0e\n\x06idUser\x18\x01 \x01(\x03\x12\x10\n\x08userName\x18\x02 \x01(\t\x12\x10\n\x08password\x18\x03 \x01(\t\"+\n\x10UserListResponse\x12\x17\n\x05users\x18\x01 \x03(\x0b\x32\x08.UserDto23\n\x0bUserService\x12$\n\x07GetList\x12\x06.Empty\x1a\x11.UserListResponseb\x06proto3')



_EMPTY = DESCRIPTOR.message_types_by_name['Empty']
_USERDTO = DESCRIPTOR.message_types_by_name['UserDto']
_USERLISTRESPONSE = DESCRIPTOR.message_types_by_name['UserListResponse']
Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:Empty)
  })
_sym_db.RegisterMessage(Empty)

UserDto = _reflection.GeneratedProtocolMessageType('UserDto', (_message.Message,), {
  'DESCRIPTOR' : _USERDTO,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:UserDto)
  })
_sym_db.RegisterMessage(UserDto)

UserListResponse = _reflection.GeneratedProtocolMessageType('UserListResponse', (_message.Message,), {
  'DESCRIPTOR' : _USERLISTRESPONSE,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:UserListResponse)
  })
_sym_db.RegisterMessage(UserListResponse)

_USERSERVICE = DESCRIPTOR.services_by_name['UserService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EMPTY._serialized_start=17
  _EMPTY._serialized_end=24
  _USERDTO._serialized_start=26
  _USERDTO._serialized_end=87
  _USERLISTRESPONSE._serialized_start=89
  _USERLISTRESPONSE._serialized_end=132
  _USERSERVICE._serialized_start=134
  _USERSERVICE._serialized_end=185
# @@protoc_insertion_point(module_scope)
